### ISSUE TITLE
Not creating a stripe customer

### ISSUE THREAD

**Issue by CiaranPearse** [alexbacanu/recommen.do#2]
Hi again,
 I have most of this up and running but a stripe customer is not being created.

I've made a few next12 apps with stripe subscriptions so I know my way around the process but cant figure this one out. Is there anything special going on thats not obvious?
 
 attempting to add a subscription from the nextjs app
<img width="1345" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/7a097b99-b4a9-4d2b-af31-b1edf07f4685">

Stripe dashboard (no webhook calls etc.) Keys/ngrok domains are correct in my .env
<img width="1175" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/eff1466f-4397-4f01-ac5f-afc32f42f1e3">

Appwrite profile table (email, name etc are populating fine)
<img width="623" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/2afe9f96-c549-4bc4-a57d-c86418f2493d">

Nothing is actually logged from here so I don't think its even being called
<img width="556" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/382db6af-500a-4422-9781-f62f5d82d2f4">

**Comment by alexbacanu** [comment]
Hey,

The issue seems to be that the stripe customer is not created on profile creation.

Please check that you have created a webhook that triggers every time a profile is created. In Appwrite you can find that under Appwrite -> Project -> Settings -> Webhooks.
It should point to the `/api/stripe/customer` and should trigger on `databases.main.collections.profile.documents.*.create`. 

It should look like this: 
![image](https://github.com/alexbacanu/recommen.do/assets/12121946/a00d6935-e7b5-4752-aff1-4b654d0b9e33)

If this webhook is set up, it should work.

EDIT: Make sure that the url points to an internet accesible one (use ngrok domain), not localhost or relative path.
Once you create the webhook, make sure to update the `APPWRITE_WEBHOOK_KEY` in the .env variables, otherwise the api will respond with a 401 error "Invalid webhook signature."
