### ISSUE TITLE
Unsupported platform error

### ISSUE THREAD

**Issue by CiaranPearse** [alexbacanu/recommen.do#3]
When I try to logout from the popup or click to subscribe in the popup I get an 'Unsupported Platform' error (works fine from nextjs side)
Clicking on subscription (network):
<img width="1065" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/49f7da00-e0e2-42c6-88d2-1d339abdd5db">

Logging out (network):
<img width="1078" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/04a43207-89a2-4885-9fa9-a497fabfa978">

Also Logging out (console):
<img width="604" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/65650cc0-5210-4b7e-849a-e878d2b2c88f">

I tried adding the chrome ext ID to the hostnames in appwrite etc, but the error still persists.

**Comment by alexbacanu** [comment]
I tested my deployment on Firefox, Chrome and Edge and they seem fine, so it's most probably from Integrations > Platforms inside cloud.appwrite.io.

It should look like this:
![image](https://github.com/alexbacanu/recommen.do/assets/12121946/5b05b0fd-20b4-4795-b509-266eaab77bae)

Make sure to add a new web app, with your extension ID on the hostname, name doesn't matter. You can test it first by just adding a wildcard (*) to the hostname, test the sign out, check if it works  and then put your extension ID and check the sign out again.

**Comment by CiaranPearse** [comment]
That fixed that issue but now Im getting the following error when I try to logout
<img width="1126" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/5e4d0ce9-94e3-449d-8a1c-de93864f1f13">
The user appears logged out but the session seems to still be active
<img width="281" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/acdb84f2-3ba4-4112-8647-ecd3515e0c07">

Is there any special permission I need to add in appwrite?
right now appwrite is set to 
appwrite.mydomain.com
my vercel is set to 
app.mydomain.com
**Edit: Seems had my cloudflare for app.. set to DNS only instead of Proxy**

And all that seems to be working fine. Correct env values etc. Its just logging out doesnt clear the sessions. This is from a fresh clone of your main branch.

Thanks in advance

**Comment by CiaranPearse** [comment]
^ actually on a second pass I realize that Account is false on logout but the profile persists. Logging in with a different account persists the previous profile
<img width="399" alt="image" src="https://github.com/alexbacanu/recommen.do/assets/630810/900f0e73-5511-4f2f-968c-b6f05b60911b">

So if I login initially with me@something.com I get the correct profile
I logout and the account is false but the profile persists
I login as someone else and the Account it correct but the profile is still me@something.com

**Comment by alexbacanu** [comment]
I'll verify the logout process to make sure it clears the whole session.

Thanks for spotting this!

**Comment by alexbacanu** [comment]
I just tested on my end and the profile doesn't persist after signing out.

This might be related to the [permission issue](https://github.com/alexbacanu/recommen.do/issues/4) you opened.

Sign-out workflow works like this:

1. calls AppwriteService.signOut() (which deletes current session)
2. refetches the accounts and profile
  a. when fetching account, since no current session is active, it will throw 401 error and will set account false
  b. when fetching profile, tries to search for documents, the result is undefined (since the current account doesn't have any permission on database), it will throw an error and will set the profile false

In your case, sign out will remove the account but it will still fetch a profile, because it can find it, so you need to set the profile be read only by the user (because your appwrite database is kind of public, I could query it just by knowing your project id and endpoint url, so you need to secure it)

Alternatively, you can set 
```diff
  const signOut = async () => {
    try {
      await AppwriteService.signOut();
    } catch (error) {
      console.log("use-account.signOut.error:", error);
    } finally {
      await Promise.all([fetchAccount(), fetchProfile()]);
+      setAccount(false);
+      setProfile(false);
    }
  };
```
on `src/lib/hooks/use-account.ts`. But you should still secure your database documents 👍.

Let me know if that works out for you.

**Comment by CiaranPearse** [comment]
Thanks again

 I think I figured out the issue. I believe I had set the document security on the profile document *after* I ran the create-profile function. I deleted the profile table and the create-profile function, then recreated in the correct order and it now works perfectly. Perhaps the payload.id query only works if the permissions are set correctly on the database from the beginning? I don't know but it seems so.

So not a code problem but maybe an appwrite setting problem.
